import * as fs from "fs/promises";
import * as path from "path";
import {
  CompletedTask,
  Skill,
  SkillCandidate,
  SkillUsage,
  SkillImprovement,
  SkillMdFrontmatter,
} from "./types.js";
import { SkillRegistry } from "./registry.js";

/**
 * SkillLearner: Hermes-inspired self-improvement loop.
 *
 * Responsibilities:
 * 1. Evaluate completed tasks for skill-creation worthiness
 * 2. Auto-generate SKILL.md from successful task patterns
 * 3. Track skill usage and evaluate performance
 * 4. Suggest improvements to existing skills
 * 5. Periodically nudge user about skill creation opportunities
 */
export interface SkillRewriteCandidate {
  skill: Skill;
  improvement: SkillImprovement;
  recordedAt: number;
  status: "pending" | "approved" | "rejected" | "applied";
}

/** @internal */
export type { SkillRewriteCandidate as _SkillRewriteCandidate };

export class SkillLearner {
  private registry: SkillRegistry;
  private skillsDir: string;
  private usageLog: SkillUsage[] = [];
  private pendingCandidates: SkillCandidate[] = [];
  private rewritePool: SkillRewriteCandidate[] = [];

  constructor(registry: SkillRegistry, skillsDir?: string) {
    this.registry = registry;
    this.skillsDir = skillsDir || path.join(process.cwd(), ".rookie", "skills");
  }

  /**
   * Evaluate a completed task to determine if it should become a skill.
   *
   * Heuristics:
   * - Task was successful
   * - Task used >= 2 distinct tools
   * - Task took >= 3 messages (non-trivial)
   * - No existing skill with similar description
   */
  async evaluateForCreation(task: CompletedTask): Promise<SkillCandidate | null> {
    // Skip failed tasks
    if (!task.success) return null;

    // Skip trivial tasks (fewer than 3 tool uses)
    if (task.tools_used.length < 2) return null;

    // Skip very short tasks
    if (task.messages.length < 3) return null;

    // Check for similar existing skills
    const existingSkills = this.registry.list();
    const descLower = task.description.toLowerCase();
    const hasSimilar = existingSkills.some((s) => {
      const similarity = this.jaccardSimilarity(
        descLower.split(/\s+/),
        s.description.toLowerCase().split(/\s+/)
      );
      return similarity > 0.5;
    });

    if (hasSimilar) return null;

    // Build candidate
    const candidate: SkillCandidate = {
      name: this.generateSkillName(task.description),
      description: task.description,
      prompt: this.synthesizePrompt(task),
      tools: [...new Set(task.tools_used)],
      source: { taskId: task.id, steps: [] },
    };

    this.pendingCandidates.push(candidate);
    return candidate;
  }

  /**
   * Create a SKILL.md file from a candidate.
   */
  async createSkill(candidate: SkillCandidate): Promise<Skill> {
    // Generate SKILL.md content
    const frontmatter: SkillMdFrontmatter = {
      name: candidate.name,
      description: candidate.description,
      "user-invocable": true,
      "allowed-tools": candidate.tools.join(" "),
      context: "inline",
      model: "inherit",
    };

    const skillMd = this.serializeSkillMd(frontmatter, candidate.prompt);

    // Write to disk
    const skillDir = path.join(this.skillsDir, candidate.name);
    await fs.mkdir(skillDir, { recursive: true });
    await fs.writeFile(path.join(skillDir, "SKILL.md"), skillMd, "utf-8");

    // Register with the registry
    const skill: Skill = {
      name: candidate.name,
      version: "1.0.0",
      description: candidate.description,
      triggers: [
        { type: "command", value: `/${candidate.name}` },
        { type: "intent", value: candidate.description.toLowerCase() },
      ],
      tools: candidate.tools,
      prompt: candidate.prompt,
      examples: [],
      metadata: {
        autoGenerated: true,
        sourceTaskId: candidate.source.taskId,
        createdAt: new Date().toISOString(),
      },
    };

    this.registry.register(skill);

    // Remove from pending
    this.pendingCandidates = this.pendingCandidates.filter(
      (c) => c.name !== candidate.name
    );

    return skill;
  }

  /**
   * Record a skill usage for performance tracking.
   */
  recordUsage(usage: SkillUsage): void {
    this.usageLog.push(usage);
  }

  /**
   * Get usage statistics for all skills.
   */
  getUsageStats(): Map<string, { count: number; successRate: number; avgDuration: number }> {
    const stats = new Map<string, { count: number; success: number; totalDuration: number }>();

    for (const usage of this.usageLog) {
      const s = stats.get(usage.skillName) ?? { count: 0, success: 0, totalDuration: 0 };
      s.count++;
      if (usage.success) s.success++;
      s.totalDuration += usage.duration;
      stats.set(usage.skillName, s);
    }

    const result = new Map<string, { count: number; successRate: number; avgDuration: number }>();
    for (const [name, s] of stats) {
      result.set(name, {
        count: s.count,
        successRate: s.count > 0 ? s.success / s.count : 0,
        avgDuration: s.count > 0 ? s.totalDuration / s.count : 0,
      });
    }
    return result;
  }

  /**
   * Evaluate skill performance based on usage history.
   * Returns an improvement suggestion if the skill is underperforming.
   */
  async evaluatePerformance(
    skill: Skill,
    recentUsages?: SkillUsage[]
  ): Promise<SkillImprovement | null> {
    const usages = recentUsages || this.getUsagesFor(skill.name);

    if (usages.length < 3) return null; // Not enough data

    const successRate = usages.filter((u) => u.success).length / usages.length;
    const satisfactionRate =
      usages.filter((u) => u.userSatisfied === true).length /
      usages.filter((u) => u.userSatisfied !== undefined).length;

    // Low success rate → suggest prompt improvement
    if (successRate < 0.6) {
      const failedUsages = usages.filter((u) => !u.success);
      const commonEdits = this.extractCommonEdits(failedUsages);
      return {
        type: "prompt_update",
        before: skill.prompt.slice(0, 200),
        after: `${skill.prompt}\n\n## Common Issues\n${commonEdits}`,
        reason: `Success rate is ${(successRate * 100).toFixed(0)}% (${usages.length} uses). Adding common issue patterns.`,
      };
    }

    // Low satisfaction → suggest description update
    if (!isNaN(satisfactionRate) && satisfactionRate < 0.5) {
      return {
        type: "description_update",
        before: skill.description,
        after: skill.description,
        reason: `User satisfaction is ${(satisfactionRate * 100).toFixed(0)}%. Consider refining the skill's approach.`,
      };
    }

    // Check for tools that are always used but not in the allowed list
    const toolFrequency = new Map<string, number>();
    for (const usage of usages) {
      if (usage.userEdits) {
        for (const edit of usage.userEdits) {
          // Extract tool names from edits (heuristic)
          const toolMatch = edit.match(/(?:use|add|include)\s+(\w+)/i);
          if (toolMatch) {
            const t = toolMatch[1];
            toolFrequency.set(t, (toolFrequency.get(t) || 0) + 1);
          }
        }
      }
    }

    // If a tool is mentioned in > 50% of edits, suggest adding it
    for (const [tool, count] of toolFrequency) {
      if (count > usages.length * 0.5 && !skill.tools.includes(tool)) {
        return {
          type: "tool_update",
          before: skill.tools.join(", "),
          after: [...skill.tools, tool].join(", "),
          reason: `Tool "${tool}" was needed in ${count}/${usages.length} uses but is not in allowed-tools.`,
        };
      }
    }

    return null;
  }

  /**
   * Add a skill to the rewrite candidate pool (P2-T2).
   * Called when a skill has low performance and needs improvement.
   */
  addToRewritePool(skill: Skill, improvement: SkillImprovement): void {
    // Check if already in pool
    const existing = this.rewritePool.find(
      (c) => c.skill.name === skill.name && c.status === "pending"
    );
    if (existing) return;

    this.rewritePool.push({
      skill,
      improvement,
      recordedAt: Date.now(),
      status: "pending",
    });
  }

  /**
   * Get all pending rewrite candidates.
   */
  getRewriteCandidates(): SkillRewriteCandidate[] {
    return this.rewritePool.filter((c) => c.status === "pending");
  }

  /**
   * Approve or reject a rewrite candidate.
   */
  async processRewriteCandidate(
    skillName: string,
    action: "approve" | "reject"
  ): Promise<boolean> {
    const candidate = this.rewritePool.find(
      (c) => c.skill.name === skillName && c.status === "pending"
    );
    if (!candidate) return false;

    if (action === "approve") {
      await this.applyImprovement(candidate.skill, candidate.improvement);
      candidate.status = "applied";
    } else {
      candidate.status = "rejected";
    }
    return true;
  }

  /**
   * Scan all skills and add low-performing ones to rewrite pool.
   * Should be called periodically (e.g., via Scheduler).
   */
  async scanForRewriteCandidates(): Promise<SkillRewriteCandidate[]> {
    const candidates: SkillRewriteCandidate[] = [];

    for (const skill of this.registry.list()) {
      const improvement = await this.evaluatePerformance(skill);
      if (improvement) {
        this.addToRewritePool(skill, improvement);
        candidates.push({
          skill,
          improvement,
          recordedAt: Date.now(),
          status: "pending",
        });
      }
    }

    return candidates;
  }

  /**
   * Apply an improvement to a skill.
   * Updates both the in-memory registry and the SKILL.md on disk.
   */
  async applyImprovement(
    skill: Skill,
    improvement: SkillImprovement
  ): Promise<void> {
    switch (improvement.type) {
      case "prompt_update":
        skill.prompt = improvement.after;
        break;
      case "description_update":
        skill.description = improvement.after;
        break;
      case "tool_update":
        skill.tools = improvement.after.split(", ").map((t) => t.trim());
        break;
    }

    // Update registry
    this.registry.register(skill);

    // Update SKILL.md on disk if it exists
    const sourcePath = skill.metadata?.["sourcePath"] as string | undefined;
    if (sourcePath) {
      try {
        const content = await fs.readFile(sourcePath, "utf-8");
        const updated = this.applyImprovementToMd(content, improvement);
        await fs.writeFile(sourcePath, updated, "utf-8");
      } catch {
        // File not found — persist as JSON fallback
      }
    }
  }

  /**
   * Start periodic nudge: remind the user about pending skill candidates.
   * @param intervalSteps Number of agent steps between nudges
   */
  scheduleNudge(intervalSteps: number): void {
    // In a real implementation, this hooks into the agent's step counter.
    // For now, use a simple counter tracked externally.
    this._nudgeInterval = intervalSteps;
    this._stepCount = 0;
  }

  private _nudgeInterval = 0;
  private _stepCount = 0;

  /**
   * Called by the agent after each step.
   * Returns a nudge message if it's time, otherwise null.
   */
  onAgentStep(): string | null {
    if (this._nudgeInterval <= 0) return null;
    this._stepCount++;

    if (this._stepCount % this._nudgeInterval !== 0) return null;
    if (this.pendingCandidates.length === 0) return null;

    const candidate = this.pendingCandidates[0];
    return (
      `💡 I noticed a pattern that could become a reusable skill: "${candidate.description}". ` +
      `Would you like me to create a SKILL.md for it? (/${candidate.name})`
    );
  }

  /**
   * Get all pending skill candidates.
   */
  getPendingCandidates(): SkillCandidate[] {
    return [...this.pendingCandidates];
  }

  // ── Internal helpers ─────────────────────────────────────

  private getUsagesFor(skillName: string): SkillUsage[] {
    return this.usageLog.filter((u) => u.skillName === skillName);
  }

  private generateSkillName(description: string): string {
    return description
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);
  }

  private synthesizePrompt(task: CompletedTask): string {
    const toolList = [...new Set(task.tools_used)]
      .map((t) => `- ${t}`)
      .join("\n");

    // Extract the user's intent from the first message
    const userMessages = task.messages.filter((m) => m.role === "user");
    const intent = userMessages[0]?.content || task.description;

    return `${intent}

## Available Tools
${toolList}

## Steps
${this.extractStepsFromMessages(task.messages)}
`;
  }

  private extractStepsFromMessages(
    messages: Array<{ role: string; content: string }>
  ): string {
    const steps: string[] = [];
    let stepNum = 1;

    for (const msg of messages) {
      if (msg.role === "assistant" && msg.content.length > 20) {
        // Extract the first sentence as a step description
        const firstSentence = msg.content.split(/[.!?\n]/)[0]?.trim();
        if (firstSentence && firstSentence.length > 10) {
          steps.push(`${stepNum}. ${firstSentence}`);
          stepNum++;
        }
      }
    }

    return steps.length > 0 ? steps.join("\n") : "1. Analyze the request\n2. Implement the solution\n3. Verify the result";
  }

  private jaccardSimilarity(a: string[], b: string[]): number {
    const setA = new Set(a);
    const setB = new Set(b);
    const intersection = new Set([...setA].filter((x) => setB.has(x)));
    const union = new Set([...setA, ...setB]);
    return union.size === 0 ? 0 : intersection.size / union.size;
  }

  private extractCommonEdits(failedUsages: SkillUsage[]): string {
    const edits: string[] = [];
    for (const usage of failedUsages) {
      if (usage.userEdits) {
        edits.push(...usage.userEdits);
      }
    }
    // Deduplicate and return top 5
    const unique = [...new Set(edits)].slice(0, 5);
    return unique.length > 0
      ? unique.map((e) => `- ${e}`).join("\n")
      : "- No specific edit patterns detected yet";
  }

  private serializeSkillMd(frontmatter: SkillMdFrontmatter, body: string): string {
    const fm = Object.entries(frontmatter)
      .filter(([, v]) => v !== undefined && v !== null)
      .map(([k, v]) => `${k}: ${v}`)
      .join("\n");

    return `---\n${fm}\n---\n\n${body}\n`;
  }

  private applyImprovementToMd(
    content: string,
    improvement: SkillImprovement
  ): string {
    switch (improvement.type) {
      case "prompt_update": {
        // Replace everything after the frontmatter
        const fmEnd = content.indexOf("---", 3);
        if (fmEnd === -1) return content;
        const afterFm = fmEnd + 3;
        return content.slice(0, afterFm) + "\n\n" + improvement.after + "\n";
      }
      case "description_update": {
        // Update the description line in frontmatter
        return content.replace(
          /^description:.*$/m,
          `description: ${improvement.after}`
        );
      }
      case "tool_update": {
        // Update allowed-tools line
        return content.replace(
          /^allowed-tools:.*$/m,
          `allowed-tools: ${improvement.after}`
        );
      }
      default:
        return content;
    }
  }
}
