export interface Trigger {
  type: "command" | "pattern" | "intent";
  value: string;
}

export interface Example {
  input: string;
  output: string;
  context?: string;
}

export interface Skill {
  name: string;
  version: string;
  description: string;
  author?: string;
  triggers: Trigger[];
  tools: string[]; // tool names, not full Tool objects
  prompt: string;
  examples: Example[];
  metadata?: Record<string, unknown>;
}

export interface SkillManifest {
  schema_version: string;
  skill: Skill;
  created_at: string;
  updated_at: string;
}

export interface CompletedTask {
  id: string;
  description: string;
  messages: Array<{ role: string; content: string }>;
  tools_used: string[];
  success: boolean;
}

// ── SKILL.md format types (Phase 2) ──────────────────────

/**
 * SKILL.md frontmatter fields.
 * Parsed from YAML between --- delimiters at top of SKILL.md.
 */
export interface SkillMdFrontmatter {
  name: string;
  description: string;
  "disable-model-invocation"?: boolean;
  "user-invocable"?: boolean;
  "allowed-tools"?: string;           // space-separated tool names
  context?: "inline" | "fork";        // inline = same agent, fork = subagent
  agent?: string;                     // agent type for fork mode (e.g. "Coder")
  model?: string;                     // "inherit" or specific model name
}

/**
 * A fully parsed SKILL.md skill, ready for registration.
 */
export interface SkillMd {
  frontmatter: SkillMdFrontmatter;
  prompt: string;                     // raw prompt body (may contain !`cmd` placeholders)
  resolvedPrompt?: string;            // prompt after shell preprocessing
  sourcePath: string;                 // absolute path to the SKILL.md file
}

/**
 * Candidate skill generated by SkillLearner from a completed task.
 */
export interface SkillCandidate {
  name: string;
  description: string;
  prompt: string;
  tools: string[];
  source: { taskId: string; steps: unknown[] };
}

/**
 * Tracking data for a single skill usage.
 */
export interface SkillUsage {
  skillName: string;
  timestamp: number;
  success: boolean;
  userSatisfied?: boolean;
  userEdits?: string[];
  duration: number;
}

/**
 * An improvement suggestion generated by SkillLearner.
 */
export interface SkillImprovement {
  type: "prompt_update" | "tool_update" | "description_update";
  before: string;
  after: string;
  reason: string;
}

export interface SkillEntry {
  id: string;
  name: string;
  description: string;
  triggers: Trigger[];
  tools: string[];
  metadata?: Record<string, unknown>;
}
