name: Bug Report
 description: Report a bug
title: "[Bug] "
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
  - type: input
    attributes:
      label: Version
      description: Package or CLI version
  - type: dropdown
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
